# Provider bindings are generated by running cdktf get.
# See https://cdk.tf/provider-generation for more details.
import ...gen.providers.kubernetes as kubernetes
kubernetes.deployment.Deployment(self, "example",
    metadata={
        "labels": {
            "test": "MyExampleApp"
        },
        "name": "terraform-example"
    },
    spec={
        "replicas": 3,
        "selector": {
            "match_labels": {
                "test": "MyExampleApp"
            }
        },
        "template": {
            "metadata": {
                "labels": {
                    "test": "MyExampleApp"
                }
            },
            "spec": {
                "container": [{
                    "image": "nginx:1.21.6",
                    "liveness_probe": {
                        "http_get": {
                            "http_header": [{
                                "name": "X-Custom-Header",
                                "value": "Awesome"
                            }
                            ],
                            "path": "/",
                            "port": 80
                        },
                        "initial_delay_seconds": 3,
                        "period_seconds": 3
                    },
                    "name": "example",
                    "resources": {
                        "limits": {
                            "cpu": "0.5",
                            "memory": "512Mi"
                        },
                        "requests": {
                            "cpu": "250m",
                            "memory": "50Mi"
                        }
                    }
                }
                ]
            }
        }
    }
)
