/*Provider bindings are generated by running cdktf get.
See https://cdk.tf/provider-generation for more details.*/
import * as kubernetes from "./.gen/providers/kubernetes";
import { Construct } from "constructs";

export class MyConvertedCode extends Construct {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    new kubernetes.deployment.Deployment(this, "example", {
      metadata: {
        labels: {
          test: "MyExampleApp",
        },
        name: "terraform-example",
      },
      spec: {
        replicas: "3",
        selector: {
          matchLabels: {
            test: "MyExampleApp",
          },
        },
        template: {
          metadata: {
            labels: {
              test: "MyExampleApp",
            },
          },
          spec: {
            container: [
              {
                image: "nginx:1.21.6",
                livenessProbe: {
                  httpGet: {
                    httpHeader: [
                      {
                        name: "X-Custom-Header",
                        value: "Awesome",
                      },
                    ],
                    path: "/",
                    port: "80",
                  },
                  initialDelaySeconds: 3,
                  periodSeconds: 3,
                },
                name: "example",
                resources: {
                  limits: {
                    cpu: "0.5",
                    memory: "512Mi",
                  },
                  requests: {
                    cpu: "250m",
                    memory: "50Mi",
                  },
                },
              },
            ],
          },
        },
      },
    });
  }
}
